name: Weekly Recap to Discord
on:
  schedule:
    # Sep 2025 (CDT, UTC-5) → 14:15 UTC
    - cron: "15 14 9,16,23,30 9 *"
    # Oct 2025 (CDT) → 14:15 UTC
    - cron: "15 14 7,14,21,28 10 *"
    # Nov 2025 (CST, UTC-6) → 15:15 UTC
    - cron: "15 15 4,11,18,25 11 *"
    # Dec 2025 (CST) → 15:15 UTC
    - cron: "15 15 2,9,16,23,30 12 *"
    # Final recap after Week 18: Tue Jan 6, 2026 @ 9:15 AM Central (CST → 15:15 UTC)
    - cron: "15 15 6 1 *"
  workflow_dispatch: {}     # lets you run it manually

jobs:
  recap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node post_weekly_recap.js
        env:
          LEAGUE_ID: "1259729726277160960"
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
